CREATE TABLE IF NOT EXISTS `rating` (
`postNumber` int(16) NOT NULL,
  `email` varchar(320) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` int(11) NOT NULL,
  `bedrooms` int(11) NOT NULL,
  `bathrooms` int(11) NOT NULL,
  `leaseLength` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `furnished` tinyint(1) NOT NULL,
  `leaseType` int(11) NOT NULL,
  `lateFee` int(11) NOT NULL,
  `lateDays` int(11) NOT NULL,
  `paymentMethods` int(11) NOT NULL,
  `deposit` int(11) NOT NULL,
  `depositReturned` int(11) NOT NULL,
  `receiptGiven` tinyint(1) NOT NULL,
  `utilities` int(11) NOT NULL,
  `appliances` int(11) NOT NULL,
  `cooling` int(11) NOT NULL,
  `heating` tinyint(1) NOT NULL,
  `parking` int(11) NOT NULL,
  `smoking` tinyint(1) NOT NULL,
  `petsAllowed` tinyint(1) NOT NULL,
  `petDeposit` int(11) NOT NULL,
  `petWeight` int(11) NOT NULL,
  `petSize` int(11) NOT NULL,
  `lawnMaintenance` tinyint(1) NOT NULL,
  `responseTime` int(11) NOT NULL,
  `maintenanceTime` int(11) NOT NULL,
  `maintenanceQuality` varchar(140) COLLATE utf8mb4_unicode_ci NOT NULL,
  `overallThoughts` varchar(140) COLLATE utf8mb4_unicode_ci NOT NULL,
  `overallRating` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
